### ISSUE TITLE
Public Release Date

### ISSUE THREAD

**Issue by atulkakrana** [MIT-LCP/mimic-iv#1]
Hi,
Can you tell us when this data be released for public use?

**Comment by alistairewj** [comment]
We hope to publish the data relatively soon, around May.

**Comment by wllwang8** [comment]
Hi,
I also want to know when the data will be published. 

In fact, I have completed the online application according to the information on the website.
_https://mimic-iv.mit.edu/about/access/_
Is it necessary to complete the above information again when the data be published?

**Comment by alistairewj** [comment]
It's public now! :)
https://physionet.org/content/mimiciv/
