### ISSUE TITLE
Admission Diagnosis

### ISSUE THREAD

**Issue by rashed120** [MIT-LCP/mimic-iv#106]
I am exploring MIMIC IV database, I was wondering is there any way to get admission diagnosis related information , i need to find out  why patients admitted to hospital.

**Comment by alistairewj** [comment]
There is no structured documentation of admission diagnosis unfortunately. In the future when the notes are released one possibility is parsing the history of present illness section. We are also hoping to incorporate the problem list from the ICU information system but this info would only be available on ICU admission and we have no timeline for that data. For now, you'll have to be a bit creative using either measurement data or carefully selected discharge diagnoses.

**Comment by alistairewj** [comment]
Discharge diagnoses are in [diagnoses_icd](https://mimic-iv.mit.edu/docs/datasets/hosp/diagnoses_icd/). Measure data is all across the database and that really depends on your study.
