### ISSUE TITLE
Is there any change of the defination of icustay in compare with mimic-III and eICU

### ISSUE THREAD

**Issue by hlblade** [MIT-LCP/mimic-iv#11]
Hi,
Thanks very much for your great work.

I want to know how many icu patients were included in mimic-iv, so  I queried the data via bigQuery with this sql string:
`SELECT count(distinct hadm_id) as hadm,count(distinct subject_id) as subject,count(distinct stay_id) as stay FROM physionet-data.mimic_icu.icustays`
and I found there were only 50k+ patients with about 69k+ icustay were documented.

I am very curious about the result, because from the patients table, we can find more then 383k unique patients and previous eICU database included 200k+ icustay entries. 

So,  was I wrong?

Any comments will be appreciated!

**Comment by yugangjia** [comment]
I get the same results. My understand is that dataset also has emergency room visits, so not every patients will have an ICU stay.

**Comment by alistairewj** [comment]
Yes, correct. The idea for mimic_core is to contain ED/ICU patients. As a result, most patients in mimic_core will not go the the ICU (and not be in mimic_icu).

The MIMIC-ED data will give information about the ED patients. It's not yet available however.

Finally, the ICU stays are only merged into the same stay_id if they are consecutive. This is different from MIMIC-III, where any ICU stays within 24 hours were merged together.

**Comment by hlblade** [comment]
Thanks very much for your reply.
