### ISSUE TITLE
Some derived concepts missing on BigQuery

### ISSUE THREAD

**Issue by JHLiu7** [MIT-LCP/mimic-iv#110]
Thanks for the new release on both the dataset and the codebase! I noticed the `make_concepts.sh` to create derived views does not include all the queries in the concept directory. I wonder if that is causing `stay_id` in tables like `physionet-data.mimic_derived.sepsis3` on BigQuery to be out of joint with the rest of the dataset. I also couldn't find tables for `charlson` and `kdigo_*`. Did I miss anything? Thanks!

**Comment by alistairewj** [comment]
Oh I didn't realize make concepts wasn't exhaustive. Let me take a look!

**Comment by alistairewj** [comment]
Should be fixed now!

**Comment by JHLiu7** [comment]
Great! But just to let you know, I think `physionet-data.mimic_derived.sepsis3` is empty right now. The other tables look good to me though

**Comment by alistairewj** [comment]
Ah thanks, it's there now.. need to figure out a better way to order the table builds in `make_concepts.sh` beyond the brittle if statements.
