### ISSUE TITLE
Any plans to do FHIR or OMOP conversion?

### ISSUE THREAD

**Issue by banderlog** [MIT-LCP/mimic-iv#119]
Any plans to do FHIR or OMOP conversion, for compatibility?

**Comment by tompollard** [comment]
Hi @banderlog, MIMIC-IV -> OMOP is in the works (see: https://github.com/OHDSI/MIMIC). When the initial version is complete, it will be released on PhysioNet. 

We'd love to transform MIMIC-IV to a FHIR representation, but our lab at MIT is not working on this currently. We are aware of various efforts in this area by other research groups.

**Comment by banderlog** [comment]
Thank you for the answer)
