### ISSUE TITLE
Data is not sequetial yet

### ISSUE THREAD

**Issue by VikNim** [MIT-LCP/mimic-iv#124]
The data is not sequential in MIMIC IV, the hadm_ids are random and not according to patient's admissions. 
Currently I am analyzing the patient records according to admittime from core.admissions 

The hadm_id should be in increasing order as per patient admissions, I believe. 
MIMIC updated its datasets recently, but still same scenario. I am attaching the details for one record for sample.
Please look at the order of admittime and hadm_id. The records is sorted according to admittime in descending manner.

**Comment by tompollard** [comment]
@VikNim the `hadm_id` is a random number assigned to each individual stay. There is no reason that it should increase sequentially with `admittime`. I have removed your screenshot of the data.

**Comment by VikNim** [comment]
@tompollard Thank you for quick response.
So, to analyze the patient's admissions we have only admittime OR is there any other we can do that ?
