### ISSUE TITLE
Data in MIMIC-IV has only three modules while the documentation lists six modules. "Note module not to be seen".

### ISSUE THREAD

**Issue by Reshma-U** [MIT-LCP/mimic-iv#129]
The MIMIC-IV data downloaded from https://physionet.org/ includes only three modules namely core, hosp, and ICU, while the MIMIC-IV website https://mimic-iv.mit.edu/docs/datasets/ contains six modules listed with ED, CXR, and Note appended in it. While ED is still not made publicly available, CXR can be accessed with a data use agreement but the Note module that contains free-text notes from EHRs is not to be seen anywhere for download. 

Could you please provide the means to access the Notes data?

**Comment by arielhasidim** [comment]
As the documentation [here](https://mimic-iv.mit.edu/docs/datasets/cxr/) stated, `In order to access this module, you must sign the data use agreement for MIMIC-CXR and request access to MIMIC-CXR data on BigQuery via the` [MIMIC-CXR PhysioNet project page](https://physionet.org/content/mimic-cxr/2.0.0/)

<img width="1337" alt="Screen Shot 2021-04-17 at 19 29 35" src="https://user-images.githubusercontent.com/23483971/115119980-bafc6e80-9fb3-11eb-939f-759b28ad15f0.png">

**Comment by Reshma-U** [comment]
Dear Ariel,

Thank you for the acknowledgment, but I have not been asking for access to CXR as I have already mentioned that it could be accessed via the data use agreement. I require access to the "Note" module. Are there any means to get access to the Note data that contains free-text notes from EHRs?

If anyone is aware of this please do let me know the way out.

**Comment by arielhasidim** [comment]
> Dear Ariel,
> 
> 
> 
> Thank you for the acknowledgment, but I have not been asking for access to CXR as I have already mentioned that it could be accessed via the data use agreement. I require access to the "Note" module. Are there any means to get access to the Note data that contains free-text notes from EHRs?
> 
> 
> 
> If anyone is aware of this please do let me know the way out.

Sorry, you are right- I didnt read carefully enough. I renoved the misleading comment.

I looked again and only found the [old notes](https://mimic.physionet.org/mimictables/noteevents/) (mimic iii 1.4), so i think you are right and the dataset is missing.

Maybe the documentation should state this until the dataset will be available. Good luck.

**Comment by alistairewj** [comment]
The notes will be made publicly available in August.
