### ISSUE TITLE
issue loading hcpcsevents with postgresql

### ISSUE THREAD

**Issue by corcra** [MIT-LCP/mimic-iv#131]
I am getting this issue running `load_gz.sql`:
```
psql:load_gz.sql:58: ERROR:  invalid input syntax for type timestamp: "99219"
CONTEXT:  COPY hcpcsevents, line 2, column chartdate: "99219"
```

I think the issue might be that the script for building the hcpcsevents table seems to expect a timestamp column: https://github.com/MIT-LCP/mimic-iv/blob/da0339348c283835dd01788f6c17d1fceb99c88e/buildmimic/postgres/create.sql#L183 but the data (mimic-iv-0.4) only has these columns:
`subject_id,hadm_id,hcpcs_cd,seq_num,short_description`

psql version is 13.2 if relevant

**Comment by tompollard** [comment]
Hi @corcra please update to the latest version of MIMIC-IV (v1.0): https://physionet.org/content/mimiciv/1.0/

**Comment by tompollard** [comment]
It looks like the error is a result of `hcpcs_cd` being inserted into the chartdate column (see change below between 0.4 and 1.0): 

![Screen Shot 2021-04-20 at 14 05 25](https://user-images.githubusercontent.com/822601/115443683-8c63db00-a1e1-11eb-80eb-3c148f977969.png)


![Screen Shot 2021-04-20 at 14 05 32](https://user-images.githubusercontent.com/822601/115443663-85d56380-a1e1-11eb-8de9-8117dac615f6.png)

**Comment by alistairewj** [comment]
If only we had a metadata file which we could check against ... wouldn't that just be swell @tompollard ? :)

**Comment by tompollard** [comment]
I \*almost\* opened the PR a few days ago...will get onto it!

**Comment by corcra** [comment]
Using the correct version of MIMIC has solved my problem, thanks!
