### ISSUE TITLE
Do we have clinical notes (e.g. echo_data) in mimic-iv?

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-iv#14]
FYI

**Comment by sudarshan85** [comment]
Hi,
Do we have a clinical notes (like `noteevents` in MIMIC III) in MIMIC IV?

**Comment by alistairewj** [comment]
Not yet!

**Comment by yugangjia** [comment]
I believe so, but I never touched that data.
Best Regards
Yugang Jia, Ph.D.  |  Verily Life Science - Data Scientist |
yugang@verily.com | 7812189680
