### ISSUE TITLE
charevents table: difference between column "error" in MIMICIII and column "warning" in MIMICIV

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-iv#15]
In some scripts for MIMICIII dataset, the error column is used to exclude certain rows using the following statement
" (error IS NULL OR error = 0)"
However, this column does not exist in MIMIVIV dataset, shall we just ignore such statement moving forward?
Or shall we use the "warning" column instead?
Thanks

**Comment by alistairewj** [comment]
We have removed all error rows prior to release so you no longer need this
statement. Warning is different and it's up to you how to handle them, but
they don't necessarily mean bad quality data.
