### ISSUE TITLE
Chartevents

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-iv#16]
It seems that the page explaining this table is not updated to MIMICIV
For example, "charttime" is not in the MIMICIV
Also there is a lot of variables not expained.

Shall I use the "starttime" to approximate "charttime" in MIMICIV?

**Comment by alistairewj** [comment]
Can you be specific in what is documented that is inconsistent with the data?

**Comment by yugangjia** [comment]
This is about the carevue and I think you already answered that question. Thanks
