### ISSUE TITLE
Question about reference

### ISSUE THREAD

**Issue by StevenWilliams** [MIT-LCP/mimic-iv#18]
Hi,

What are the reference requirements for students who don't yet have a formal supervisor? What should the reference be able to confirm and do they have to be from the same institution?

**Comment by alistairewj** [comment]
I've spoken with our administrator, who told me that he'd handle this on a case by case basis.

> This is an impossible question to answer globally.  In a case like this, I'd ask the student for clarification.  We do require that students be supervised by someone on faculty or in a senior research position at the student's school or university.  If there's some sort of cross-registration going on, then a supervisor from a different institution might be okay, depending on the specifics.  But the important concept is supervision -- I want to make sure that there really is someone responsible paying attention to the student's work.

Please contact mimic-support@physionet.org with more information about your situation. Thanks!
