### ISSUE TITLE
Inputevents - is this table the same as the inputevents_mv in MIMIC-III

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-iv#19]
Hi, 
This table does not exist in MIMIC-III.
Shall we consider this one is similar to inputevents_mv in MIMIC-III?
To re-use the code for MIMIC-III, shall we create the charttime variable?

**Comment by alistairewj** [comment]
Yes, inputevents_mv from MIMIC-III is the same as inputevents in MIMIC-IV. There is no need to create charttime, any code referencing inputevents_cv can be deleted in the upgrade.

**Comment by yugangjia** [comment]
Thanks!
