### ISSUE TITLE
Logic to calculate the pivoted_sofa

### ISSUE THREAD

**Issue by yugangjia** [MIT-LCP/mimic-iv#33]
Hi, 
I am running the code to calculate pivoted_sofa for MIMIC-IV and I found something interesting.
To calculate the respiration_24hours or other values for 24 hours, do we use the recent measurement in last 24 hours?
If there is multiple measure from last 24 hours, it seems that we are using the maximum/minimum value from last 24 hours, not the recent one.
Is this correct?

![image](https://user-images.githubusercontent.com/22260846/93484807-5ae40380-f8d0-11ea-8834-b67636099b96.png)
Thanks

**Comment by alistairewj** [comment]
Yep, I based this off the original paper:

>The participants decided: (1) to limit the number of organs studied to 6. As an example, attempting to include dysfunction/failure of the gut was felt to be very important, but also too complex and was therefore abandoned. (2) To use a score from 0 (normal) to 4 (most abnormal) for each organ. **(3) To record the worst values on each day.**

I can see the value in having the most recent value drive the SOFA score, but I think taking the worst value is more consistent. It means that the SOFA at hours 24, 48, 72, etc... are equivalent to SOFA day 1, day 2, day , etc.

[Original paper here](https://www.researchgate.net/profile/Rui_Moreno/publication/14361654_The_SOFA_Sepsis-related_Organ_Failure_Assessment_score_to_describe_organ_dysfunctionfailure_On_behalf_of_the_Working_Group_on_Sepsis-Related_Problems_of_the_European_Society_of_Intensive_Care_Medicine/links/0c960536cf4f20aef4000000.pdf).
