### ISSUE TITLE
subject_ids between mimic iii and mimic iv

### ISSUE THREAD

**Issue by aliforgetti** [MIT-LCP/mimic-iv#34]
Just wanted to know if the subject_ids are consistent in both mimic iii and mimic iv. Is it possible to link between the two?
Also since mimic iii ends in 2012 and mimic iv starts in 2008 what is the possibility of overlap of subjects between these two?

**Comment by rubyliu007** [comment]
The same problem is also found in the stay_id entry of MIMIC 3 and MIMIC 4. We found that the stay_id of MIMIC3 and MIMic4 did not overlap, but the two databases should have overlapping patients from 2008 to 2012. Could I use ID to find out the patients only in MIMIC4 after 2012

**Comment by adigoryl** [comment]
I have started using mimic-iv and got to a stage in my project where I need to extract [signs & symptoms on admission] and [co-morbidities & risk factors]. In mimic-iv, this data belongs in the Emergency Department module which is not yet available. However, I have noticed that this data is available in mimiciii-clinical, which makes me wonder if there is any connection between the subject_id and hadm_id of the two mimic versions? 

Any guidance would be much appreciated,
Adrian.

**Comment by adigoryl** [comment]
@alistairewj

**Comment by alistairewj** [comment]
There is no link between the identifiers. We highly recommend not mixing databases as there are overlapping subjects, and many analysis assumptions (e.g. I. I. D.) would be violated. We will update MIMIC-III in the future to remove patients so that it may be analyzed with MIMIC-IV. For now I would recommend learning MIMIC-IV!

**Comment by adigoryl** [comment]
Thank you for the response, Alistair. Unfortuenly, this is not the answer I wished for.

Any idea on when the Emergency Department module in mimic-iv could be available? I have been working on mimic-iv for over a month now and it would be a waste to rewrite everything I have done using mimic-iii.

**Comment by alistairewj** [comment]
No timeline unfortunately. I do try to get the data out as fast as I can.
