### ISSUE TITLE
How would I calculate age at admit (e.g. for hospitalization)?

### ISSUE THREAD

**Issue by gkovaig** [MIT-LCP/mimic-iv#41]
I see anchor_age in mimic_core.patients and admittime in mimic_core.admissions, but there does not seem to be the equivalent of calculating age_at_admit from MIMIC-III:
`SELECT DATE_DIFF(DATE(icu.intime), DATE(pat.dob), YEAR) AS age`
`FROM `physionet-data.mimiciii_demo.icustays` AS icu`
`INNER JOIN `physionet-data.mimiciii_demo.patients` AS pat`
`  ON icu.subject_id = pat.subject_id;`

**Comment by gkovaig** [comment]
Haven't heard back from anyone in a week.

From https://mimic-iv.mit.edu/docs/datasets/core/patients/:
ANCHOR_AGE, ANCHOR_YEAR, and ANCHOR_YEAR_SHIFTED are intended to be analyzed together. The ANCHOR_AGE is the age of the patient in the given ANCHOR_YEAR/ANCHOR_YEAR_SHIFTED. In order to determine the age of a patient on admission to the hospital, it is necessary to account for the number of years between ANCHOR_YEAR_SHIFTED and their hospital admission time.

Should the equivalent MIMIC-IV code be something like this?

SELECT (EXTRACT(YEAR FROM icu.intime) - pat.anchor_year + pat.anchor_age) as age_at_admit,
FROM `physionet-data.mimic_core.patients` AS pat
        inner join `physionet-data.mimic_icu.icustays` AS icu
            on pat.subject_id = icu.subject_id

**Comment by alistairewj** [comment]
Yes! That's exactly how we envisaged `anchor_year` to be used (I edited your query for formatting/one typo).

**Comment by gkovaig** [comment]
Thank you Alistair
