### ISSUE TITLE
noteevents 

### ISSUE THREAD

**Issue by sexbee** [MIT-LCP/mimic-iv#44]
Which table in mimic-iv is used to be substitute for noteevents in mimic-iii ？

**Comment by alistairewj** [comment]
There isn't a table yet and we need to figure this out. Our current plan is to have a `mimic_hosp.note` and `mimic_hosp.note_detail` table.

**Comment by vs74** [comment]
> There isn't a table yet and we need to figure this out. Our current plan is to have a `mimic_hosp.note` and `mimic_hosp.note_detail` table.

@alistairewj may I know when do you plan to release the `mimic_hosp.note` and `mimic_host.note_detail` tables in the mimic-iv database?

**Comment by alistairewj** [comment]
We ultimately decided to separate the notes from MIMIC-IV. No timeline on their release.
