### ISSUE TITLE
Dimension table: microbiology items

### ISSUE THREAD

**Issue by vizer1993** [MIT-LCP/mimic-iv#47]
Is there an alternative table to _d_micro_ in v0.4? Unable to process _microbiologyevents_ since _d_micro_ has been removed. Thanks. 

Alternatively, has _d_micro_ been incorporated into _microbiologyevents_ in v0.4?

**Comment by alistairewj** [comment]
What in particular are you looking for?

>

**Comment by vizer1993** [comment]
Fixed the issue myself. Thanks.
