### ISSUE TITLE
Some problems encountered when running the sql file in the concepts folder

### ISSUE THREAD

**Issue by xujiameng** [MIT-LCP/mimic-iv#58]
I am very grateful to PhysioNet for providing such a great medical database. Working in the medical big data industry made me realize how valuable these data are.
       Maybe it's because mimic-iv is still under development. When I run the sql file in concepts like mimic-iii or e-ICU, I found that the mimic_derived architecture used in ../durations/ventilator_durations.sql is not installed. I inquired about the documents and information I could think of but couldn't find the corresponding installation method.
       How should I install mimic_derived architecture?

**Comment by xujiameng** [comment]
![image](https://user-images.githubusercontent.com/37614092/99016099-52870c80-2591-11eb-858f-c6b36a73d7f7.png)

**Comment by judywawira** [comment]
how did you resolve this?

**Comment by xujiameng** [comment]
> how did you resolve this?

The SQL program in the concepts folder is missing some necessary tables. I recommend using bigquery to access mimic_derived, which is comprehensive. You can also try to save the data on bigquery to Google cloud , and then download it locally. But I think bigquery can satisfy general access

**Comment by alistairewj** [comment]
Also this shouldn't be a problem anymore. The ventilator durations query no longer exists: there's now `measurement/oxygen_delivery.sql`, `measurement/ventilator_setting.sql`, and `treatment/ventilation.sql`.  Ultimately the *ventilation* table takes the place of what was previously called *ventdurations*. There is still some improvement possible in the ventilation queries, but they should work now.

I plan on adding the ability to port the queries to PostgreSQL in the future, similar to what is done in the MIMIC-III code repo (a shell script converts the BigQuery syntax into PostgreSQL compatible syntax). Not 100% sure it's a solution that's easy for everyone to implement, but it works OK for those on Mac/Unix. The README in mimic-code talks about it a bit: https://github.com/MIT-LCP/mimic-code/tree/master/concepts
