### ISSUE TITLE
How should I install the schemas, mimic_derived, mentioned in concepts?

### ISSUE THREAD

**Issue by xujiameng** [MIT-LCP/mimic-iv#59]
I am very grateful to PhysioNet for providing such a great medical database. Working in the medical big data industry made me realize how valuable these data are.
   Maybe it's because mimic-iv is still under development. When I run the sql file in concepts like mimic-iii or e-ICU, I found that the mimic_derived used in ..concepts/durations/ventilator_durations.sql is not installed. I inquired about the documents and information I could think of but couldn't find the corresponding installation method.
   How should I install mimic_derived  ?

**Comment by xujiameng** [comment]
![image](https://user-images.githubusercontent.com/37614092/99022830-553c2e80-259e-11eb-97cf-5361766223cf.png)

**Comment by zln199206** [comment]
Dear
      Teacher Xu
      Hello, is the problem of "install the schemas, mimic_derived" solved? I have the same problem as you, thank you. Looking forward to your reply.

**Comment by xujiameng** [comment]
> 尊敬的
> 徐老师
> 您好，“安装模式，micic_derived”的问题解决了吗？我和你有同样的问题，谢谢。期待你的回复。

非常遗憾，我没有太多精力放在这上面，目前还没有解决这一问题。

**Comment by xujiameng** [comment]
> Dear
> Teacher Xu
> Hello, is the problem of "install the schemas, mimic_derived" solved? I have the same problem as you, thank you. Looking forward to your reply.

在test文件夹的README.md中我找到了些关于mimic_derived的描述。我尝试通过BigQuery获取mimic_derived的相关代码。不过很不幸，在BigQuery界面没能找到Pin a project的方法（也许开通试用后能解决这一问题，不过我没有注册需要的相关银行账号。如果你感兴趣可以通过https://github.com/freefq/free中提供的ssr节点翻墙查看）

**Comment by xujiameng** [comment]
> Dear
> Teacher Xu
> Hello, is the problem of "install the schemas, mimic_derived" solved? I have the same problem as you, thank you. Looking forward to your reply.

没有必要浪费时间登陆BigQuery了。里面只有eicu与mimiciii数据库。目前没有mimic-iv相关的任何内容

**Comment by alistairewj** [comment]
> > Dear
> > Teacher Xu
> > Hello, is the problem of "install the schemas, mimic_derived" solved? I have the same problem as you, thank you. Looking forward to your reply.
> 
> 在test文件夹的README.md中我找到了些关于mimic_derived的描述。我尝试通过BigQuery获取mimic_derived的相关代码。不过很不幸，在BigQuery界面没能找到Pin a project的方法（也许开通试用后能解决这一问题，不过我没有注册需要的相关银行账号。如果你感兴趣可以通过https://github.com/freefq/free中提供的ssr节点翻墙查看

You don't need to pin MIMIC-IV. All PhysioNet datasets are under the project `physionet-data`. The MIMIC-IV, MIMIC-III, and eICU datasets are stored within `physionet-data`. If you have access they'll appear there.

> 没有必要浪费时间登陆BigQuery了。里面只有eicu与mimiciii数据库。目前没有mimic-iv相关的任何内容

This is not necessarily true. In order to see MIMIC-IV on BigQuery, you must separately request access via the PhysioNet MIMIC-IV page. If you do that, you should then be able to find the MIMIC-IV tables, including mimic_derived. If you cannot then let me know.

> I am very grateful to PhysioNet for providing such a great medical database. Working in the medical big data industry made me realize how valuable these data are.
> Maybe it's because mimic-iv is still under development. When I run the sql file in concepts like mimic-iii or e-ICU, I found that the mimic_derived used in ..concepts/durations/ventilator_durations.sql is not installed. I inquired about the documents and information I could think of but couldn't find the corresponding installation method.
> How should I install mimic_derived ?

You guessed right - still in development! You should be able to request access to BigQuery on the MIMIC-IV PhysioNet page. Under the `physionet-data` dataset there should be `mimic_derived`. I haven't had time to build/test it for postgres yet unfortunately, and in particular the ventilation queries are incomplete.

**Comment by xujiameng** [comment]
> > > Dear
> > > Teacher Xu
> > > Hello, is the problem of "install the schemas, mimic_derived" solved? I have the same problem as you, thank you. Looking forward to your reply.
> > 
> > 
> > 在test文件夹的README.md中我找到了些关于mimic_derived的描述。我尝试通过BigQuery获取mimic_derived的相关代码。不过很不幸，在BigQuery界面没能找到Pin a project的方法（也许开通试用后能解决这一问题，不过我没有注册需要的相关银行账号。如果你感兴趣可以通过[https://github.com/freefq/free中提供的ssr节点翻墙查看](https://github.com/freefq/free%E4%B8%AD%E6%8F%90%E4%BE%9B%E7%9A%84ssr%E8%8A%82%E7%82%B9%E7%BF%BB%E5%A2%99%E6%9F%A5%E7%9C%8B)
> 
> You don't need to pin MIMIC-IV. All PhysioNet datasets are under the project `physionet-data`. The MIMIC-IV, MIMIC-III, and eICU datasets are stored within `physionet-data`. If you have access they'll appear there.
> 
> > 没有必要浪费时间登陆BigQuery了。里面只有eicu与mimiciii数据库。目前没有mimic-iv相关的任何内容
> 
> This is not necessarily true. In order to see MIMIC-IV on BigQuery, you must separately request access via the PhysioNet MIMIC-IV page. If you do that, you should then be able to find the MIMIC-IV tables, including mimic_derived. If you cannot then let me know.
> 
> > I am very grateful to PhysioNet for providing such a great medical database. Working in the medical big data industry made me realize how valuable these data are.
> > Maybe it's because mimic-iv is still under development. When I run the sql file in concepts like mimic-iii or e-ICU, I found that the mimic_derived used in ..concepts/durations/ventilator_durations.sql is not installed. I inquired about the documents and information I could think of but couldn't find the corresponding installation method.
> > How should I install mimic_derived ?
> 
> You guessed right - still in development! You should be able to request access to BigQuery on the MIMIC-IV PhysioNet page. Under the `physionet-data` dataset there should be `mimic_derived`. I haven't had time to build/test it for postgres yet unfortunately, and in particular the ventilation queries are incomplete.

Thank you very much for your advice. With authorization on the mimic IV interface, I can now view mimic_derived in bigquery.  It's difficult to log in to Google in China. If possible, I prefer to query data locally. I haven't been exposed to MySQL, but if the code of MySQL can successfully create mimic_derived, I will be very happy to learn it.

**Comment by cosgriffc** [comment]
If you have MIMIC-III installed locally then the concepts in `mimic-derived` can be manually run using the code found here: https://github.com/MIT-LCP/mimic-code/tree/master/concepts

**Comment by xujiameng** [comment]
.
