### ISSUE TITLE
Numbers of prolonged ventilation cases in mimic-iv compared to mimic-iii

### ISSUE THREAD

**Issue by JHLiu7** [MIT-LCP/mimic-iv#65]
Thanks a lot for the great effort put into the new dataset! I have a question about the number of prolonged ventilation based on the derived tables on Big Query. 

Using the `ventilation_durations` table for MIMIC-III (under `mimiciii_derived`), I'm able to query _3561_ cases (unique ICU stays) with vent duration longer than 7days, _1203_ longer than 14days, and _555_ longer than 21days. However, when checking out the `ventilator_durations` table for MIMIC-IV (under `mimic_derived`) and calculating hourly durations by `DATETIME_DIFF`, I only got _2337_ (7days), _549_ (14days), _157_ (21days).

I wonder why there're some gaps there. Was this a population change or if I missed/misused anything? Thanks a lot!

**Comment by alistairewj** [comment]
Sorry the query for MIMIC-IV is still being tweaked. There is an issue right now in mixing up non-invasive and invasive ventilation. There is a population change though, so the numbers won't exactly match between MIMIC-III and MIMIC-IV.

**Comment by JHLiu7** [comment]
Got it! Thanks for the quick response!
