### ISSUE TITLE
dod field in patient table are all blank?

### ISSUE THREAD

**Issue by jinjinzhou** [MIT-LCP/mimic-iv#71]
Is it intended to be missing?

**Comment by alistairewj** [comment]
Certainly not!

**Comment by jinjinzhou** [comment]
But when I queried in GCP BigQuery (see below) it shows "This query returned no results." And when I open `patients` table in core folder, `dod` field are all blank.  

SELECT *
FROM `physionet-data.mimic_core.patients`
where dod IS NOT NULL;

**Comment by alistairewj** [comment]
Yes sorry I went off to investigate after seeing this :) You are right about it being all blank and this is a bug.

We've dropped our old source of date of death (the social security death master file), and it looks like I haven't updated the code to reflect this. For now, you can use the earliest `deathtime` in the admissions table. The patient's `dod` will be derived from this in the next version.

**Comment by jinjinzhou** [comment]
I see. Thanks.

**Comment by hidoyebi** [comment]
Hello. Can I ask you a question here?

> For now, you can use the earliest deathtime in the admissions table.

What is the meaning of the earliest deathtime? Could you tell me more detail about deathtime?

**Comment by alistairewj** [comment]
Sometimes there are organ donor accounts (very rare as we try to remove them) - but in those cases there may be two `hadm_id` for the same subject and the earlier one was their date of death.

Info on `deathtime` is on the docs: https://mimic-iv.mit.edu/docs/datasets/core/admissions/

**Comment by hidoyebi** [comment]
Thank you so much :)

**Comment by alistairewj** [comment]
In MIMIC-IV v1.0, `dod` is now populated using `deathtime` from the admissions table. https://mimic-iv.mit.edu/docs/overview/changelog/#mimic-iv-v10
