### ISSUE TITLE
Availability of pediatric population data in mimic-iv 

### ISSUE THREAD

**Issue by guolin1** [MIT-LCP/mimic-iv#76]
Will future releases include ICU & Hosp data for pediatric population between ages 1 and 17 in the? It seems like currently the minimum age in the ICU module is 18, and those that are less than 18 are all neonates.

Thank you.

**Comment by alistairewj** [comment]
Data are sourced from a hospital without a pediatric ICU so unfortunately it's not possible.

**Comment by guolin1** [comment]
Thank you for the quick response!
