### ISSUE TITLE
Documentation for Timestamps: which timezone?

### ISSUE THREAD

**Issue by KrishnaPG** [MIT-LCP/mimic-iv#80]
Kindly clarify which time zone the timestamps in the data refers to? For example, `admittime`, `dischtime` etc. in the `admissions` table, are they UTC time zone or some other, such as EST, PST etc?

Also, for each field, kindly provide few sample values in the documentation so that we can understand the nature of the data to expect when creating the DB schemas. 

For example, while indicating the data as `TIMESTAMP` data type is fine, it would not be clear in which exact format the timestamp is stored in the file (such as `unix timestamp` format or the `yyyy-mm-dd` format or some other) unless we uncompress the whole file and load it into some kind large editor to review couple of entries.

Documenting some sample values for each of the fields can greatly enhance the schema understanding without having to unpack the large data files.

**Comment by alistairewj** [comment]
> Kindly clarify which time zone the timestamps in the data refers to? For example, `admittime`, `dischtime` etc. in the `admissions` table, are they UTC time zone or some other, such as EST, PST etc?

All times are stored in US/Eastern.

> Also, for each field, kindly provide few sample values in the documentation so that we can understand the nature of the data to expect when creating the DB schemas.
> 
> For example, while indicating the data as `TIMESTAMP` data type is fine, it would not be clear in which exact format the timestamp is stored in the file (such as `unix timestamp` format or the `yyyy-mm-dd` format or some other) unless we uncompress the whole file and load it into some kind large editor to review couple of entries.

PostgreSQL only accepts timestamp data directly from CSV in the format `YYYY-MM-DD HH:MI:SS`, where `HH` is using a 24 minute clock, e.g. `2184-01-30 18:45:00`. All timestamps are in that format.

> Documenting some sample values for each of the fields can greatly enhance the schema understanding without having to unpack the large data files.

Sure! If you have suggestions where exactly it could go or even better could make a PR around this we'd be happy to merge it.
