### ISSUE TITLE
How to verify if the data is loaded correctly?

### ISSUE THREAD

**Issue by KrishnaPG** [MIT-LCP/mimic-iv#81]
It would be great if the documentation could provide some `verifiable statistics` that will allow us to verify if the data we loaded into our databases is indeed loaded correctly and records are not missing or not having incorrect values.

For example, the `patients` table seems to be having `383220` records and none of them seem to have `dod`. 

- That sounds concerning since there is no way to confirm if this is correct (without having to open the csv files and thoroughly verifying line by line) 

Also, there seems to be `60879` records with `anchor_age == 0`

- As per the [documentation](https://mimic-iv.mit.edu/docs/datasets/core/patients/) those patients are of zero age ? Are we talking about just born babies? 
- How to confirm if this is not a data loading error on our side?

In the documentation if you could kindly provide some additional basic statistics for each table , such as the number of rows, min and max values for each field, and the count for each group (such as `anchor_year_group`) etc. it would greatly assure us that our loading programs are correct and that we are not deriving results on incorrectly loaded data.

This is similar to `unit test cases` in the software engineering, and we need these `unit test cases` for the data to ensure its integrity.

**Comment by alistairewj** [comment]
We used to have a checks file that we haven't created yet for PostgreSQL but I agree it's a good idea to do so. Comparing the total row counts seemed sufficient to verify the data were loaded correctly. In addition there are SHA256 sums available which you could verify locally before loading the data.

**Comment by KrishnaPG** [comment]
Thank you @alistairewj Row count verification while necessary, it is not sufficient. For example, as stated earlier, we are observing 

- patients table with `383220` records and none of them seem to have `dod`.

Is that correct?

- Also, there seems to be `60879` records with `anchor_age == 0`

Is that correct?

**Comment by KrishnaPG** [comment]
Came across this data-quality project: [OHDSI Data Quality Dashboard](https://github.com/OHDSI/DataQualityDashboard) based on [Kahn Framework](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5051581/)  and that seems to be something that can address the data quality verification needs for large data sets, such as this.

May be Mimic 4 can look into adopting something similar.

**Comment by tompollard** [comment]
@KrishnaPG we are currently working on a project to create a transformed version of MIMIC-IV in the OMOP common data model. This should allow the data to be explored using OHDSI tools like the one that you mention. When an initial version is ready, it will be made available on PhysioNet.

**Comment by alistairewj** [comment]
> 
> 
> Thank you @alistairewj Row count verification while necessary, it is not sufficient. For example, as stated earlier, we are observing
> 
>     * patients table with `383220` records and none of them seem to have `dod`.
> 
> 
> Is that correct?

Nope! It's a bug, tracked here #71. It's correctly loaded in.

>     * Also, there seems to be `60879` records with `anchor_age == 0`
> 
> 
> Is that correct?

Yes, that's correct. The problem is there are infinite possible checks to do here and only some make sense. Our original approach is (1) checksum the downloaded files, and (2) validate row counts. I think this is good enough for ensuring integrity in the data load. Certainly makes no assertions about data quality however!

**Comment by KrishnaPG** [comment]
Thank you @tompollard Looking forward to the OMOP model.

**Comment by KrishnaPG** [comment]
@alistairewj Thank you for confirming the presence `anchor_age == 0` records. 

It is, however, not clear what does age = 0 mean here:
- As per the [documentation](https://mimic-iv.mit.edu/docs/datasets/core/patients/) those patients are of zero age ? Are we talking about just born babies?
