### ISSUE TITLE
Dischtime and Deathtime

### ISSUE THREAD

**Issue by finnickniu** [MIT-LCP/mimic-iv#88]
Hi there,

In the Admission.csv, I found there is a column called DISTHTIME, and I compared it with OUTTIME in icustay.csv. I found part of the ICU out time is bigger than the discharged time of the same subject, and some of them are classified as death, but some are not. How can I understand this? Is that so? or Is it a mistake?

**Comment by alistairewj** [comment]
Sometimes there are inconsistencies as the discharge times are all entered administratively. You should find it rare that an `outtime` is later than a `dischtime`. If you quantify your findings to get a sense of the scope it would make it easier to judge whether these are simply typographical errors or the result of a bigger issue.
