### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by ggg5438** [MIT-LCP/mimic-iv#89]
Vidio links are not working!

**Comment by alistairewj** [comment]
Which ones?

**Comment by ggg5438** [comment]
Both. ([https://www.chilconference.org/tutorial_d.html](https://www.chilconference.org/tutorial_d.html)) and [https://www.chilconference.org/tutorial_f.html]((https://www.chilconference.org/tutorial_f.html))

They show 404 error.

**Comment by alistairewj** [comment]
Sorry - what I mean is - where are they linked to in the docs? Will make it easier to fix the links.

**Comment by ggg5438** [comment]
The tutorial page is
[https://mimic-iv.mit.edu/docs/tutorials/video/](https://mimic-iv.mit.edu/docs/tutorials/video/)
