### ISSUE TITLE
How should one cite MIMIC-IV in papers?

### ISSUE THREAD

**Issue by wenh06** [MIT-LCP/mimic-iv#90]
Is it the same as MIMIC-III?

**Comment by tompollard** [comment]
@wenh06 thanks for checking. For now I would suggest using the MIMIC-III citation (shown at: https://mimic.physionet.org/about/acknowledgments/). We will post the MIMIC-IV citation here when it is available.

If you are using a MIMIC-IV module that already has an associated publication, then please also cite this (e.g. for MIMIC-CXR, see: https://mimic-cxr.mit.edu/).

**Comment by alistairewj** [comment]
You can also use the PhysioNet citation at the top of the PhysioNet page: https://physionet.org/content/mimiciv/0.4/

We are still working on adding more data and drafting the manuscript!

**Comment by wenh06** [comment]
I got it.
