### ISSUE TITLE
What is the unit of BUN (blood urea nitrogen) in MIMIC-IV?

### ISSUE THREAD

**Issue by zixuan0922** [MIT-LCP/mimic-iv#95]
I wondered if the unit of BUN (blood urea nitrogen) is mg/dL since there's a 'None' in 'unitname' column in both d_items.csv and d_labitems.csv. Thanks!

**Comment by alistairewj** [comment]
Mean Platelet Volume (MPV) exists in the BIDMC lab catalogue (which becomes *d_labitems*), but there's no measurements so far as I can find. I think they just don't measure it. This behavior will exist for other labs in *d_labitems* as well, as we don't filter the catalogue to `itemid` with measurements in *labevents*.

To double check, I did a cursory scan of the discharge summaries, and it only turned up measurements from outside hospitals.
