### ISSUE TITLE
Missing data of Mean Platelets Volume (MPV) in labevents table

### ISSUE THREAD

**Issue by zixuan0922** [MIT-LCP/mimic-iv#96]
Hi!

There's no data for Mean Platelets Volume (MPV) in labevents.csv but it has an itemid (52137) in d_labitems.csv. I wondered if it exists under a different name or the itemid is wrong.

Thanks!

**Comment by alistairewj** [comment]
I replied to #95 as well which I'll quote here:

> Mean Platelet Volume (MPV) exists in the BIDMC lab catalogue (which becomes d_labitems), but there's no measurements so far as I can find. I think they just don't measure it. This behavior will exist for other labs in d_labitems as well, as we don't filter the catalogue to itemid with measurements in labevents.
> 
> To double check, I did a cursory scan of the discharge summaries, and it only turned up measurements from outside hospitals.
