### ISSUE TITLE
hosp - prescriptions - rate of Vasopressin

### ISSUE THREAD

**Issue by fatemeh91** [MIT-LCP/mimic-iv#97]
Hello,
I am trying to extract the rate and amount of the vasopressin for patients who are in the Emergency Department.  I could not find the amount and the rate of Vasopressin for these patients. The prescription table has the quantity (i.e. dose_val_rx),  but I'm wondering to know how can i extract the amount and the rate of Vasopressin for these patients?

**Comment by alistairewj** [comment]
The amount and the rate of vasopressin administered won't be available in the prescriptions table - only the prescribed dose. There is usually hospital policy for the rate of administration of medications which can sometimes be informative. For vasopressin it is:

> Septic shock
> **Recommended initial rate:** 1.8 units/hr.
> **Titrate to:** mean arterial pressure or systolic blood pressure
> **Increase by:** up titration isnot recommended in patients with septic shock
> **Decrease by:** Vasopressin can be discontinued at a dose of ≤ 2.4 units/hr. Down titration is optional, may decrease by 0.6 units/hr every 30minutes to reduce the risk of hypotension.
> **Recommended maximum rate:** 1.8 units/hr.

For the patients admitted to the hospital when eMAR was available, you can use eMAR to determine the exact dose administered. A good way to filter to eMAR patients is to those hospitalizations with at least 1 eMAR observation.

**Comment by alistairewj** [comment]
Note also the extensive discussion regarding vasopressin here: https://github.com/MIT-LCP/mimic-code/issues/844

**Comment by fatemeh91** [comment]
Thaks.
